[build]
  command = "solid-start build"
  functions = "netlify/functions"
  publish = "netlify"
[[redirects]]
  from = "*"
  to = "https://www.calmosis.com"
  status = 301
  force = true

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
